services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
  
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_tarefas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always      
    volumes:
      - polls_mysql_data:/var/lib/mysql
  
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 3000:80
        depends_on:
            - mysql

volumes:
  polls_mysql_data:
